apiVersion: kubean.io/v1alpha1
kind: ClusterOperation
metadata:
  name: cluster1-offline-demo-ops-1
  labels:
    clusterName: cluster1-offline-demo
spec:
  cluster: cluster1-offline-demo
  image: ghcr.io/kubean-io/spray-job # or add specific tag, such as v0.4.0
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: playbook
      action: ping.yml
    - actionType: playbook
      action: enable-repo.yml
      extraArgs: |
        -e "{repo_list: ['http://MINIO_API_HOST:MINIO_API_PORT/kubean/centos/\$releasever/os/\$basearch']}"
    - actionType: playbook
      action: disable-firewalld.yml
    - actionType: playbook
      action: remove-pkgs.yml
  postHook:
    - actionType: playbook
      action: cluster-info.yml
