apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: KubeanInfoManifestNAME
spec:
  kubesprayVersion: ""
  kubeanVersion: ""
  docker:
    - os: "redhat-7"
      defaultVersion: ""
      versionRange: [ ]
    - os: "debian"
      defaultVersion: ""
      versionRange: [ ]
    - os: "ubuntu"
      defaultVersion: ""
      versionRange: [ ]
  components:
    - name: "cni"
      defaultVersion: ""
      versionRange: [ ]
    - name: "containerd"
      defaultVersion: ""
      versionRange: [ ]
    - name: "kube"
      defaultVersion: ""
      versionRange: [ ]
    - name: "calico"
      defaultVersion: ""
      versionRange: [ ]
    - name: "cilium"
      defaultVersion: ""
      versionRange: [ ]
    - name: "flannel"
      versionRange: [ ]
    - name: "kube-ovn"
      versionRange: [ ]
    - name: "etcd"
      defaultVersion: ""
      versionRange: [ ]
