apiVersion: kubean.io/v1alpha1
kind: ClusterOperation
metadata:
  name: cluster2-airgap-install-ops
spec:
  cluster: cluster2-airgap
  image: ghcr.m.daocloud.io/kubean-io/spray-job:<TAG> # Please replace <TAG> with the specified version, such as v0.4.9
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: playbook
      action: ping.yml
    - actionType: playbook
      action: enable-repo.yml
      extraArgs: |
        -e "{repo_list: ['http://<MINIO_API_HOST>:<MINIO_API_PORT>/kubean/centos/\$releasever/os/\$basearch']}"
    - actionType: playbook
      action: disable-firewalld.yml
    - actionType: playbook
      action: remove-pkgs.yml
  postHook:
    - actionType: playbook
      action: cluster-info.yml
