# Copyright 2023 Authors of kubean-io
# SPDX-License-Identifier: Apache-2.0

---
## Only for RHEL 8 on offline environment currently
- name: Remove packages
  hosts: k8s_cluster
  become: true
  vars:
    rhel_enable_repos: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: Remove fuse package
      package: 
        name: fuse
        state: absent
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"
        - not rhel_enable_repos
        - container_manager == "docker"

    - name: Remove extra packages
      package: 
        name: "{{ item }}"
        state: absent
      with_items:
        - audit
        - runc
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"
        - not rhel_enable_repos