name: kubean_compatibility_schedule

on:
  # refer: https://crontab.guru/examples.html
  # At 00:00 on every Sunday（Beijing Time).
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0'

env:
  KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
  KUBESPRAY_IMAGE_NAME: kubespray
  SPRAY_JOB_IMAGE_NAME: spray-job
  KUBESPRAY_TAG: latest
  VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
  VSPHERE_PASSWD: ${{ secrets.VSPHERE_PASSWD }}
  AMD_ROOT_PASSWORD: ${{ secrets.AMD_ROOT_PASSWORD }}
  KYLIN_VM_PASSWORD: ${{ secrets.KYLIN_VM_PASSWORD }}

jobs:
  auto-kubean-compatibility:
    runs-on: [self-hosted, online]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: kubean_compatibility_schedule
        run: |
          CONTAINER_TAG=$(git describe --tags --abbrev=8 --dirty)
          HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1 }'`
          TAG_SECOND_PART=`echo ${CONTAINER_TAG}|awk  -F "-" '{print $2 }'`
          if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then 
            HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1"-"$2 }'`
          fi
          echo ${{ runner.name }}
          echo ${{ github.workspace }}
          echo "${HELM_CHART_VERSION}" 
          echo "${CONTAINER_TAG}"
          bash hack/e2e.sh "${HELM_CHART_VERSION}" "${CONTAINER_TAG}" ${{ runner.name }} "${VSPHERE_USER}" "${VSPHERE_PASSWD}" "${AMD_ROOT_PASSWORD}" "${KYLIN_VM_PASSWORD}" "KUBEAN-COMPATIBILITY"
