name: Auto Release CI

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
    - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

env:
  ENVIRONMENT_RUNS_ON: ubuntu-latest
  ENVIRONMENT_CD: alpha

jobs:
  call-offline-build:
    uses: ./.github/workflows/call-offline-build.yaml
    permissions:
      contents: write

  call-images-build:
    uses: ./.github/workflows/call-build-imgs.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: read
    with:
      CI_TYPE: release

  call-os-pkgs-build:
    uses: ./.github/workflows/call-os-pkgs-build.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: write

  sync-charts-and-api:
    needs: [call-images-build, call-offline-build]
    uses: ./.github/workflows/call-sync-repos.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: read

  generate-release-notes:
    needs: [call-os-pkgs-build, sync-charts-and-api]
    uses: ./.github/workflows/call-gen-release-notes.yaml
    secrets: inherit

  build-docs:
    needs: generate-release-notes
    uses: ./.github/workflows/call-build-docs.yaml
    secrets: inherit
    permissions:
      contents: write

  get-environment:
    runs-on: ubuntu-latest
    needs: generate-release-notes
    outputs:
      environment_runs_on: ${{ steps.get_variables.outputs.environment_runs_on }}
      enviroment_cd: ${{ steps.get_variables.outputs.enviroment_cd }}

    steps:
    - name: Get environment variable
      id: get_variables
      run: |
        echo environment_runs_on=${{ env.ENVIRONMENT_RUNS_ON }} >> $GITHUB_OUTPUT
        echo enviroment_cd=${{ env.ENVIRONMENT_CD }} >> $GITHUB_OUTPUT

  call-cd:
    uses: ./.github/workflows/call-cd.yaml
    secrets: inherit
    needs: get-environment
    permissions:
      packages: write
      contents: read
    with:
      ENVIRONMENT_RUNS_ON: ${{ needs.get-environment.outputs.environment_runs_on }}
      ENRIRONMENT_CD: ${{ needs.get-environment.outputs.enviroment_cd }}
      CI_TYPE: release

  call_speedup_offline_packages:
    uses: ./.github/workflows/call-speedup-offline-packags.yaml
    needs: get-environment
    permissions:
      packages: write
      contents: read
