name: Build Kubean Docs

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install mkdocs-material
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox
          pip install mkdocs-awesome-pages-plugin
      - name: Build en docs
        run: |
          mkdocs build -f docs/mkdocs.zh.yml
          mkdocs build -f docs/mkdocs.en.yml
      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
