name: SPEEDUP OFFLINE PACKAGES
on: workflow_call
jobs:
  speedup_offline_packages:
      runs-on: ubuntu-latest
      continue-on-error: true
      strategy:
        fail-fast: false
        matrix:
          file_name: [ files-amd64, images-amd64, files-arm64, images-arm64, os-pkgs-centos7, os-pkgs-kylinv10, os-pkgs-redhat8, os-pkgs-redhat7 ]
      permissions:
        packages: write
        contents: read
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: wei/wget@v1
          with:
            args: -qO- https://httpbin.org/get
        - name: wget-file
          run: |
            GIT_TAG=$(git describe --tags --abbrev=8 --dirty)
            TAG=`echo ${GIT_TAG}|awk -F "-" '{print $1}'`
            TAG_SECOND_PART=`echo ${GIT_TAG}|awk  -F "-" '{print $2 }'`
            if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then 
              TAG=`echo ${GIT_TAG}|awk -F "-" '{print $1"-"$2 }'`
            fi
            echo "Start speed up ${{ matrix.file_name }}"
            echo "${TAG}"
            SPEEDUP_BASE_URL="https://github.com/kubean-io/kubean/releases/download"
            file="${SPEEDUP_BASE_URL}/${TAG}/${{ matrix.file_name }}-${TAG}.tar.gz"
            wget -q -c -T 1m ${file}
            echo "Download ${file} end"